config-version: ${global_config_version}

# The storage type of the plugin
# Available types: MYSQL, MONGODB, JSON, SQLITE
storage-type: SQLITE
storage-config:
  host: "127.0.0.1"
  port: 3306
  table-prefix: "modernfactions_"
  database: "your-database"
  username: "your-username"
  password: "your-password"
  debug: true
  # If you want to use MangoDB, please change the storage-type to MONGODB and fill this configuration
  auth-database: admin

# The type of notification when a player enters a chunk
# Options: ACTION_BAR, MESSAGE, TITLE
enter-chunk-notification:
  type: MESSAGE
  message: "%faction% ~ %faction_description%"
  #If type is TITLE
  subtitle: "%faction_description%"
  fadeIn: 10
  stay: 40
  fadeOut: 10

# The max amount of users per faction
max-users-per-faction: 10
# The max amount of power a user can have
max-user-power: 10
# The min amount of power a user can have
min-user-power: -10
# The default power of a user on first join
default-user-power: 5

# Delay to teleport a player to the faction home in seconds
delay-teleport-home: 5

# Manage format of the chat
# Available placeholders: %player% player display name,
# %faction% faction name,
# %role% role of the player in the faction,
# %relation_color% color of the relation between the sender and the receiver,
# %color_format% color of the format of chat
# %message% message of the chat
chat:
  public-format: "%relation_color%%role%%faction% <white>%player% : %message%"
  ally-format: "%color_format%%faction% %player% <white>: %message%"
  truce-format: "%color_format%%faction% %player% <white>: %message%"
  faction-format: "%color_format%%role%%faction% %player% <white>: %message%"